# Generated by Django 4.0.4 on 2022-05-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('parentezco', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida', models.CharField(max_length=40)),
                ('actividad', models.CharField(max_length=40)),
            ],
        ),
    ]
