# Generated by Django 4.0.4 on 2022-05-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('parentezco', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Familiar',
        ),
        migrations.AddField(
            model_name='gusto',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
